---
title: "CS422 Section 01"
author: "Kaiyue Ma"
output:
  html_document:
    df_print: paged
---


```{r}
#2.1 (a)
setwd("/Users/michael/Codes/R/1")
read.csv("College.csv")
college <- read.csv("College.csv")
```

```{r}
#2.1 (b)
college <- read.csv("College.csv")
rownames(college) <- college [,1]
fix(college)
```

```{r}
college <- college [ ,-1]
fix(college)
```

```{r}
#2.1 (c)
summary(college)
```

```{r}
pairs(college[,2:11])
```

```{r}
boxplot(perc.alumni~Private, data = college, xlab = "Private or not", ylab = "perc.alumni",main = "alumni donate to their colleges")
```

```{r}
boxplot (PhD~Private, data = college, xlab = "Private or not", ylab = "# PhD",main = "number of PhD student")
```

```{r}
Elite <- rep("No", nrow(college))
Elite[college$Top10perc > 50] <- "Yes"
Elite <- as.factor(Elite)
college1 <- data.frame(college, Elite)

summary (college1)
```

```{r}
par(mfrow=c(2,2))
hist(college[1:10,3],main = "Histogram of accepted(first 10 school)", xlab = "Number of accepted students")
hist(college$Books,main = "Histogram of book collection", xlab = "Number of book")
hist(college$Top10perc,main = "Histogram of Top10 Perc", xlab = "Number of students")
hist(college$Top25perc,main = "Histogram of Top25 Perc", xlab = "Number of students")

```

```{r}
cat("Continue exploring the data\n")
cat("college property & expend")
Privatecol <- subset(college, college$Private == "Yes")
Nonprivatecol <-subset(college, college$Private == "No")
mean(Privatecol$Expend)
mean(Nonprivatecol$Expend)
```



# part 2
```{r}
library(corrplot)
#2.2 (a)
setwd("/Users/michael/Codes/R/1")
nba <- read.csv("nba.csv",stringsAsFactors = F, sep = ',')
corrplot(round(cor(nba[,-1*c(1:7,16:17,20,22)]),2), method = "number")
```

```{r}
#2.2 (a) 
para1 <- lm(formula = PTS ~ FG, data = nba)
summary(para1)

cat("The model fits data at R-squared: 0.9163 ")
```

```{r}
#2.2 (b)
plot(nba$FG, nba$PTS, xlab = "FG", ylab = "PTS")
abline(para1)
```

```{r}
#2.2 (c)
c <-round(cor(nba[,-1*c(1:7,10:12,14:17,19:22)]),2)
c1 <-round(cor(nba[,c('FG','MIN','FT','A','PTS')]),2)

corrplot(c1, method = "number")
```

```{r}
# 2.2 (d)
set.seed(1122)
index <- sample(1:nrow(nba),250)
train <- nba[index,]
test <- nba[-index,]
multi <- lm(formula = PTS ~ MIN + FG + A + FT, data = train)
summary(multi)

cat("In this multi-parameters model, found that FG adn FT has significant influence on the PTS.\n")
cat("Regressor chosen are good!")

```

```{r}
# 2.2 (e)
plot(multi,1)

cat("The variance is low.")
```

```{r}
# 2.2 (f)
hist(multi$residuals, xlab = "Model Residuals", 
     main="NBA Residual Histogram MultiVariate")

cat ("Yes! It's approximimately like the Gaussian distribution.")
```

```{r}
# 2.2 (g)
testmulti<- predict(multi, test[, c('FG','MIN','FT','A')])
```

```{r}
# 2.2 (h)
result <- data.frame(test$PTS,testmulti)
result <- data.frame(result,(result$test.PTS-result$testmulti))
colnames(result) <- c("Actual", "Predicted", "Error")
RSS <- sum((result$Error)^2)
TSS <- sum((result$Actual-mean(result$Actual))^2)
RSE <- sqrt(RSS/(length(result$Actual)-4-1))
FStat <- ((TSS-RSS)/4)/(RSS/(length(result$Actual)-4-1))
cat(RSS,TSS,RSE,FStat)
```

